Tokenization with Truncation and Offset Support ad tests
IBM/vllm pull request #47
Opened 2024-06-14 23:48 UTC by fialhocoelho

- Support for Truncation and Offset: The tokenize() function has been edited to include support for truncation and offset.
- New Tests: Tests have been added to evaluate the tokenization output,  focusing on truncation and offset functionality to ensure replicability.
- Makefile Addition: A Makefile has been added to facilitate the generation of necessary files for gRPC import for `vllm/tests/test_server_tokenize_truncate.py`
- Direct Use of `tokenizer.encode_plus()`: The `tokenizer.encode_plus() `function is used directly to avoid modifying the `tokenizer_group.encode_async` function, which is part of the upstream code/project. This ensures compatibility and maintains the integrity of the upstream codebase. This implementation won't affect performance because `tokenizer_group.encode_async` doesn't run `Tokenizer.encode` in a background thread.

2024-06-16 00:44 UTC, maxdebayser commented on vllm/entrypoints/grpc/grpc_server.py
> +            )
@njhill, here the code is calling encode_plus directly because adding an async wrapper would require changing the vLLM code. But I don't think it has a performance impact because the actual encoding in encode_async not offloaded to a thread pool or anything:
```
    async def encode_async(
            self,
            prompt: str,
            request_id: Optional[str] = None,
            lora_request: Optional[LoRARequest] = None) -> List[int]:
        tokenizer = await self.get_lora_tokenizer_async(lora_request)
        ret = tokenizer.encode(prompt)
        self._raise_if_input_too_long(ret, lora_request)
        return ret
```

2024-06-20 16:43 UTC, joerunde commented
for https://github.ibm.com/ai-foundation/fmaas-inference-server/issues/515

2024-06-25 16:56 UTC, joerunde commented
@prashantgupta24 can you help coordinate getting this into the tgis adapter?

2024-06-26 18:28 UTC, prashantgupta24 requested changes

2024-06-26 18:28 UTC, prashantgupta24 commented on vllm/entrypoints/grpc/grpc_server.py
> +        service_metrics.observe_tokenization_request(request)
```suggestion
        service_metrics.count_tokenization_request(request)
```

2024-06-26 18:29 UTC, prashantgupta24 commented on vllm/entrypoints/grpc/grpc_server.py
> +        service_metrics.observe_tokenization_request(request)
I'm going to be making this change in the adapter repo

2024-07-12 23:40 UTC, njhill commented
Closing since this was ported to the vllm-tgis-adapter repo. Thanks @fialhocoelho.

2024-07-12 23:40 UTC, closed without merging